[package]
name = "dynqueue"
version = "0.4.0"
authors = ["Harald Hoyer <harald@hoyer.xyz>"]
edition = "2024"
rust-version = "1.87"

license = "MIT"
documentation = "https://docs.rs/dynqueue"
homepage = "https://github.com/haraldh/dynqueue"
repository = "https://github.com/haraldh/dynqueue"
description = "Parallel work queue that can grow dynamically while it drains"
readme = "README.md"

keywords = [ "parallel", "performance", "thread", "join", "concurrency"]
categories = [ "concurrency" ]

[dependencies]
rayon = "1"
crossbeam-queue = { version = "0.3", optional = true }
